### ISSUE TITLE
Failed to build with Zephyr v1.8.0-rc1

### ISSUE THREAD

**Issue by kiendinh** [iotivity/iotivity-constrained#5]
I tried to build the Zephyr app with Zephyr v1.8.0-rc1 and got the following build error:

$ cd port/zephyr
$  make BOARD=arduino_101 CONF_FILE=prj_bt.conf

....
/home/kien/workspace/zephyr/iotivity-constrained/port/zephyr/src/ipadapter.c:25:22: fatal error: net/nbuf.h: No such file or directory
 #include <net/nbuf.h>
                      ^
compilation terminated.
/home/kien/workspace/zephyr/zephyrLF/scripts/Makefile.build:183: recipe for target 'src/ipadapter.o' failed
make[3]: *** [src/ipadapter.o] Error 1
/home/kien/workspace/zephyr/zephyrLF/Makefile:993: recipe for target 'zephyr-app-dir' failed
make[2]: *** [zephyr-app-dir] Error 2
make[2]: Leaving directory '/home/kien/workspace/zephyr/iotivity-constrained/port/zephyr/outdir/arduino_101'
Makefile:176: recipe for target 'sub-make' failed
make[1]: *** [sub-make] Error 2
make[1]: Leaving directory '/home/kien/workspace/zephyr/zephyrLF'
/home/kien/workspace/zephyr/zephyrLF/Makefile.inc:82: recipe for target 'all' failed
make: *** [all] Error 2
...

I'm using Zephyr v1.8.0-rc1 (98e14bc) and Zephyr SDK v0.9.1. It was alright to build with Zephyr v1.7.0

**Comment by jimmy-huang** [comment]
the network api has changed in latest Zephyr including new hearders, iotivity-constrained has to be updated for the new api.

**Comment by jimmy-huang** [comment]
@kmaloor, can you please take a look?

**Comment by jimmy-huang** [comment]
patch is submitted here https://gerrit.iotivity.org/gerrit/#/c/20771/

**Comment by kmaloor** [comment]
@jimmy-huang Thank you. I've just reviewed and merged your patch.
@kiendinh You can test now with the latest master.
