### ISSUE TITLE
Unable to compile with zephyr V1.6.0

### ISSUE THREAD

**Issue by njitwb** [iotivity/iotivity-constrained#3]
Dear @kmaloor 

When I compiled the code with zephyr V1.6.0, I encountered many compilation errors. For instance, net_context_get function is defined in zephyr:
```
struct net_context *net_context_get(enum ip_protocol ip_proto,
                      const struct net_addr *remote_addr,
                      uint16_t remote_port,
                      struct net_addr *local_addr,
                      uint16_t local_port);
```
It has five parameters, but iotivity-constrained call this function with:
`ret = net_context_get(AF_INET6, SOCK_DGRAM, IPPROTO_UDP, &udp_recv6);`
I think that is the problem of the zephyr version, but when I checked out the old version of zephyr, still has five parameters.

**Comment by kmaloor** [comment]
Hello,
The Zephyr port for IoTivity-Constrained was recently updated to align with
the latest Zephyr code on the Zephyr master branch. This includes an entirely new IP
stack and new APIs that are incompatible with prior Zephyr releases.
So, please build against Zephyr master.

**Comment by njitwb** [comment]
Really works. Thank you very much. Maybe we can add the support revision of zephyr to README. The latest version on the official website is v1.6.0, it cannot work with iotivity-constrained.
